<script setup lang="ts">
import type { PublicArtistProfile } from '../domain/publicArtistProfile'
import type { AgencyCatalog } from '../domain/agencyCatalog'
import { agencyCatalogPreview, agencyMediaExtension } from '../domain/agencyCatalog'
import { getPublicArtistProfile } from '../services/publicBookingIngressApi'
const props=withDefaults(defineProps<{workspaceId:string;role:string;locale:'es'|'en';demo?:boolean}>(),{demo:false})
const emit=defineEmits<{editArtist:[id:string]}>()
const api=useAgencyCatalog(),config=useRuntimeConfig(),auth=useCueAuth()
const editable=computed(()=>['owner','admin'].includes(props.role))
const es=computed(()=>props.locale==='es')
const catalog=ref<AgencyCatalog|null>(null),visibleIds=ref<string[]>([]),loading=ref(false),saving=ref(false),error=ref(''),notice=ref('')
const savedPublished=ref(false)
const media=useArtistProfile()
const uploading=ref<'cover'|'logo'|''>('')
const mediaUrls=ref<Record<'cover'|'logo',string>>({cover:'',logo:''})
function releaseMedia(slot:'cover'|'logo'){if(mediaUrls.value[slot].startsWith('blob:'))URL.revokeObjectURL(mediaUrls.value[slot]);mediaUrls.value[slot]=''}
onUnmounted(()=>{releaseMedia('cover');releaseMedia('logo')})
async function hydrateMedia(){
 for(const slot of ['cover','logo'] as const){releaseMedia(slot);const path=catalog.value?.[slot==='cover'?'coverPath':'logoPath'];if(path){try{mediaUrls.value[slot]=await media.getCoverObjectUrl(path)}catch{error.value=es.value?'No se pudo cargar una imagen guardada. Recarga la página para reintentar.':'A saved image could not load. Reload the page to retry.'}}}
}
async function chooseMedia(event:Event,slot:'cover'|'logo'){
 const input=event.target as HTMLInputElement,file=input.files?.[0];input.value='';if(!file||!catalog.value||uploading.value||saving.value)return
 uploading.value=slot;error.value='';notice.value=''
 try{
  agencyMediaExtension(file)
  try{const bitmap=await createImageBitmap(file);bitmap.close()}catch{throw new Error('agency_media_invalid_type')}
  const workspaceId=props.workspaceId
  const path=props.demo?null:await api.upload(workspaceId,slot,file)
  if(workspaceId!==props.workspaceId)return
  releaseMedia(slot);mediaUrls.value[slot]=URL.createObjectURL(file)
  catalog.value[slot==='cover'?'coverPath':'logoPath']=path
  catalog.value[slot==='cover'?'coverUrl':'logoUrl']=null
  notice.value=es.value?'Imagen preparada. Guarda la página para aplicar el cambio.':'Image ready. Save the page to apply the change.'
 }catch(cause:any){const raw=String(cause?.message||'');error.value=raw.includes('too_large')?(es.value?'La imagen debe ocupar menos de 8 MB.':'The image must be under 8 MB.'):raw.includes('invalid_type')?(es.value?'Selecciona una imagen JPG, PNG o WebP válida.':'Choose a valid JPG, PNG or WebP image.'):(es.value?'No se pudo subir la imagen. Tu página conserva la anterior; vuelve a intentarlo.':'Upload failed. Your page keeps the previous image; please retry.')}finally{uploading.value=''}
}
function removeMedia(slot:'cover'|'logo'){if(!catalog.value)return;releaseMedia(slot);catalog.value[slot==='cover'?'coverPath':'logoPath']=null;catalog.value[slot==='cover'?'coverUrl':'logoUrl']=null;notice.value=es.value?'Guarda la página para aplicar el cambio.':'Save the page to apply the change.'}
function useMediaLink(slot:'cover'|'logo'){if(!catalog.value)return;releaseMedia(slot);catalog.value[slot==='cover'?'coverPath':'logoPath']=null}
const accountEmail=computed(()=>props.demo ? '' : auth.session.value?.user.email || '')
const emailValid=computed(()=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(catalog.value?.contactEmail?.trim() || ''))
const readyToPublish=computed(()=>Boolean(catalog.value?.bio?.trim() && emailValid.value && visibleIds.value.some(id=>catalog.value?.artists.some(a=>a.id===id&&a.eligible))))
const selectedCount=computed(()=>previewData.value?.artists.length || 0)
const previewArtistId=ref('')
const demoProfile=computed<PublicArtistProfile|null>(()=>{
 const a=catalog.value?.artists.find(a=>a.id===previewArtistId.value)
 if(!props.demo||!a)return null
 return {stageName:a.name,slug:a.slug,bio:es.value?'Ficha ficticia para revisar el recorrido Agencia → Artista → Booking. Los datos no se publican.':'Fictional profile to review Agency → Artist → Booking. This data is not published.',city:a.city,countryCode:'ES',languages:['ES','EN'],primaryGenres:a.genres,secondaryGenres:[],performanceFormats:['DJ set'],eventTypes:['Club'],yearsActive:null,websiteUrl:null,instagramUrl:null,soundcloudUrl:null,mixcloudUrl:null,youtubeUrl:null,spotifyUrl:null,coverUrl:null,coverPositionY:50,artistImageUrl:null,artistCutoutUrl:null,artistImageStyle:'photo',artistImagePositionX:50,artistImagePositionY:50,artistImageScale:1,acceptingRequests:true,bookingManagedBy:catalog.value?.name||null}
})
const previewDialog=ref<HTMLDialogElement|null>(null)
const previewData=computed(()=>catalog.value ? agencyCatalogPreview({...catalog.value,coverUrl:mediaUrls.value.cover||catalog.value.coverUrl,logoUrl:mediaUrls.value.logo||catalog.value.logoUrl},visibleIds.value) : null)
const publicUrl=computed(()=>catalog.value && import.meta.client ? `${window.location.origin}/agency/${catalog.value.slug}` : '')
const fields=[{id:'tagline',es:'Frase de portada',en:'Cover tagline',max:254},{id:'city',es:'Ciudad base',en:'Base city',max:254},{id:'coverUrl',es:'Imagen de portada · URL HTTPS',en:'Cover image · HTTPS URL',max:2048},{id:'logoUrl',es:'Logo · URL HTTPS',en:'Logo · HTTPS URL',max:2048},{id:'contactEmail',es:'Email público de booking',en:'Public booking email',max:254},{id:'instagramUrl',es:'Instagram · URL HTTPS',en:'Instagram · HTTPS URL',max:2048},{id:'websiteUrl',es:'Web · URL HTTPS',en:'Website · HTTPS URL',max:2048}] as const
async function load(){
 if(!editable.value)return
 loading.value=true;error.value=''
 try{
  catalog.value=props.demo ? {name:'CUE Test Agency',slug:'cue-test-agency',published:false,tagline:'Independent sounds. Shared direction.',bio:'Representamos artistas de club con una identidad propia. Conectamos su música con salas, festivales y proyectos que comparten nuestra visión.',city:'Barcelona / Madrid',coverUrl:null,logoUrl:null,contactEmail:'booking@example.invalid',instagramUrl:null,websiteUrl:null,artists:[{id:'demo-mara',name:'Mara Velt',slug:'mara-velt',city:'Barcelona',genres:['Techno'],catalogVisible:true,eligible:true,acceptingRequests:true},{id:'demo-nox',name:'Nox Arda',slug:'nox-arda',city:'Madrid',genres:['Electro'],catalogVisible:true,eligible:true,acceptingRequests:true}]} : await api.load(props.workspaceId)
  savedPublished.value=Boolean(catalog.value?.published)
  await hydrateMedia()
  visibleIds.value=catalog.value?.artists.filter(a=>a.catalogVisible&&a.eligible).map(a=>a.id)||[]
 }catch{error.value=es.value?'No se pudo cargar la página de agencia.':'Could not load the agency page.'}finally{loading.value=false}
}
watch(()=>[props.workspaceId,props.role],load,{immediate:true})
async function save(){
 if(catalog.value?.published&&!readyToPublish.value){error.value=es.value?'Completa la presentación, el email de booking y selecciona al menos una ficha preparada.':'Complete the bio, booking email and select at least one ready artist.';return}
 if(!editable.value||!catalog.value||saving.value||uploading.value)return
 saving.value=true;error.value='';notice.value=''
 try{
  if(!props.demo) catalog.value=await api.save(props.workspaceId,catalog.value,visibleIds.value)
  savedPublished.value=Boolean(catalog.value.published)
  notice.value=props.demo ? (es.value?'Simulación guardada en esta preview. No se ha publicado.':'Saved in this preview only. Nothing was published.') : es.value?'Página guardada.':'Page saved.'
 }catch(cause:any){ const raw=String(cause?.data?.message||cause?.message||'');error.value=raw.includes('catalog_publication_incomplete') ? (es.value?'Para publicar, añade presentación, email y al menos un artista preparado.':'Add a bio, email and at least one ready artist to publish.') : raw.includes('catalog_artist_not_ready') ? (es.value?'Hay una ficha que ya no está preparada. Recarga y revisa su perfil público y gestión del booking.':'An artist is no longer ready. Reload and check public profile and booking management.') : es.value?'No se pudo guardar. Revisa los campos y las URLs HTTPS.':'Could not save. Check the fields and HTTPS URLs.' }finally{saving.value=false}
}
async function openPreview(){
 if(!catalog.value)return
 previewArtistId.value=''
 error.value=''
 if(!props.demo) await Promise.all(catalog.value.artists.filter(a=>a.eligible&&visibleIds.value.includes(a.id)).map(async a=>{try{const profile=await getPublicArtistProfile(String(config.public.supabaseUrl),a.slug);a.imageUrl=profile.artistImageUrl;a.coverUrl=profile.coverUrl}catch{a.imageUrl=null;a.coverUrl=null}}))
 previewDialog.value?.showModal()
}
async function copyLink(){try{await navigator.clipboard.writeText(publicUrl.value);notice.value=es.value?'Enlace copiado.':'Link copied.'}catch{notice.value=publicUrl.value}}
</script>
<template>
 <section v-if="editable" class="agency-catalog-editor">
  <header class="agency-catalog-editor__heading"><div><p class="agency-catalog-editor__label">{{ es ? 'AGENCIA / PÁGINA PÚBLICA' : 'AGENCY / PUBLIC PAGE' }}</p><h2>{{ es ? 'Presenta tu agencia.' : 'Present your agency.' }}</h2><p>{{ es ? 'Prepara tu página, elige los artistas y compártela con promotores.' : 'Prepare your page, choose artists and share it with promoters.' }}</p></div><span class="agency-catalog-editor__status">{{ savedPublished ? (es?'Publicada':'Published') : (es?'Borrador · privado':'Draft · private') }}</span></header>
  <p v-if="loading" role="status">{{ es ? 'Cargando página…' : 'Loading page…' }}</p>
  <p v-if="error" role="alert" class="agency-catalog-editor__error">{{ error }} <button v-if="!catalog" type="button" @click="load">{{ es ? 'Reintentar' : 'Retry' }}</button></p>
  <form v-if="catalog" @submit.prevent="save">
   <fieldset :disabled="saving||Boolean(uploading)" class="agency-catalog-editor__group"><legend>{{ es?'01 / Identidad':'01 / Identity' }}</legend><p>{{ catalog.name }} · {{ es?'Tu página tendrá la identidad de esta agencia.':'Your page represents this agency.' }}</p>
    <div class="agency-catalog-editor__fields"><label v-for="field in fields.filter(f=>['tagline','city'].includes(f.id))" :key="field.id"><span>{{ es ? field.es : field.en }}</span><input v-model="catalog[field.id]" type="text" :maxlength="field.max"></label></div>
    <label class="agency-catalog-editor__field"><span>{{ es ? 'Presentación de la agencia' : 'About the agency' }}</span><textarea v-model="catalog.bio" maxlength="4000" rows="4" :required="catalog.published" :placeholder="es?'Qué artistas representas y cómo trabaja tu agencia.':'Who you represent and how your agency works.'" /></label>
    <div class="agency-catalog-editor__media-grid"><section v-for="slot in (['cover','logo'] as const)" :key="slot" class="agency-catalog-editor__media"><h3>{{ slot==='cover'?(es?'Portada':'Cover'):'Logo' }} <small>{{ es?'Opcional':'Optional' }}</small></h3><div class="agency-catalog-editor__media-preview" :class="{'is-logo':slot==='logo'}"><img v-if="mediaUrls[slot]||catalog[slot==='cover'?'coverUrl':'logoUrl']" :src="mediaUrls[slot]||catalog[slot==='cover'?'coverUrl':'logoUrl']||undefined" :alt="slot==='cover'?(es?'Portada de la agencia':'Agency cover'):(es?'Logo de la agencia':'Agency logo')"><span v-else>{{ slot==='cover'?(es?'La imagen que abre tu página':'Your page opening image'):(es?'La firma de tu agencia':'Your agency identity') }}</span></div><p>{{ slot==='cover'?(es?'Mejor una foto horizontal, 1600 × 900 px o más.':'A landscape photo, 1600 × 900 px or larger works best.'):(es?'Usa PNG o WebP con fondo transparente.':'Use PNG or WebP with a transparent background.') }}</p><div class="agency-catalog-editor__media-actions"><label class="agency-catalog-editor__media-picker"><span>{{ uploading===slot?(es?'Subiendo…':'Uploading…'):(es?'Elegir imagen':'Choose image') }}</span><input type="file" accept="image/jpeg,image/png,image/webp" :aria-label="slot==='cover'?(es?'Elegir portada':'Choose cover'):(es?'Elegir logo':'Choose logo')" @change="chooseMedia($event,slot)"></label><button v-if="mediaUrls[slot]||catalog[slot==='cover'?'coverUrl':'logoUrl']||catalog[slot==='cover'?'coverPath':'logoPath']" type="button" @click="removeMedia(slot)">{{ es?'Quitar':'Remove' }}</button></div></section></div><p>{{ es?'JPG, PNG o WebP · máximo 8 MB por imagen. Guarda la página para aplicar los cambios.':'JPG, PNG or WebP · maximum 8 MB per image. Save the page to apply changes.' }}</p><details class="agency-catalog-editor__optional"><summary>{{ es?'Usar enlaces de imagen':'Use image links' }}</summary><div class="agency-catalog-editor__fields"><label v-for="field in fields.filter(f=>['coverUrl','logoUrl'].includes(f.id))" :key="field.id"><span>{{ es?field.es:field.en }}</span><input v-model="catalog[field.id]" type="url" :maxlength="field.max" placeholder="https://…" @input="useMediaLink(field.id==='coverUrl'?'cover':'logo')"></label></div></details>
   </fieldset>
   <fieldset :disabled="saving||Boolean(uploading)" class="agency-catalog-editor__group"><legend>{{ es?'02 / Contacto de booking':'02 / Booking contact' }}</legend>
    <label class="agency-catalog-editor__field"><span>{{ es?'Email público de la agencia':'Agency public email' }}</span><input v-model="catalog.contactEmail" type="email" autocomplete="email" maxlength="254" :required="catalog.published" placeholder="booking@tuagencia.com" aria-describedby="agency-contact-help"></label>
    <p id="agency-contact-help">{{ es?'Este email aparece en tu página como contacto. No conecta un buzón ni cambia el remitente de Cuebooker. Las solicitudes por ficha llegan a Bookings.':'This email appears on your page as a contact. It does not connect a mailbox or change the Cuebooker sender. Profile enquiries arrive in Bookings.' }}</p>
    <button v-if="accountEmail&&!catalog.contactEmail" type="button" @click="catalog.contactEmail=accountEmail">{{ es?'Usar mi email de acceso':'Use my sign-in email' }} · {{ accountEmail }}</button>
    <p v-if="!catalog.contactEmail" class="agency-catalog-editor__hint">{{ es?'Añade el correo que quieres hacer público antes de publicar.':'Add the email you want to make public before publishing.' }}</p>
    <details class="agency-catalog-editor__optional"><summary>{{ es?'Enlaces de la agencia · opcional':'Agency links · optional' }}</summary><p>{{ es?'Añádelos si ayudan a presentar tu agencia. Puedes dejar ambos vacíos.':'Add these if they help present your agency. Both can stay empty.' }}</p><div class="agency-catalog-editor__fields"><label v-for="field in fields.filter(f=>['instagramUrl','websiteUrl'].includes(f.id))" :key="field.id"><span>{{ es?field.es:field.en }}</span><input v-model="catalog[field.id]" type="url" :maxlength="field.max" placeholder="https://…"></label></div></details>
   </fieldset>
   <fieldset :disabled="saving||Boolean(uploading)" class="agency-catalog-editor__group"><legend>{{ es?'03 / Artistas del catálogo':'03 / Catalogue artists' }}</legend><p>{{ es?'Selecciona quién aparece en la página. Añadir un artista al roster privado no publica su ficha.':'Choose who appears on the page. Adding an artist to your private roster does not publish their profile.' }}</p>
    <div v-for="artist in catalog.artists" :key="artist.id" class="agency-catalog-editor__artist" :class="{'is-selected':visibleIds.includes(artist.id)&&artist.eligible}"><label><input v-model="visibleIds" type="checkbox" :value="artist.id" :disabled="!artist.eligible"><span><strong>{{ artist.name }}</strong><small>{{ artist.eligible ? (es?'Perfil público preparado':'Public profile ready') : (es?'Activa su perfil público y asigna el booking a esta agencia.':'Enable the public profile and assign bookings to this agency.') }}</small></span></label><button type="button" @click="emit('editArtist',artist.id)">{{ es?'Editar ficha':'Edit record' }}</button></div>
    <p v-if="!catalog.artists.length">{{ es?'Añade tu primer artista desde Artistas.':'Add your first artist from Artists.' }}</p><p v-else>{{ selectedCount }} {{ es?'artistas seleccionados para la página':'artists selected for the page' }}</p>
   </fieldset>
   <fieldset :disabled="saving||Boolean(uploading)" class="agency-catalog-editor__group agency-catalog-editor__publication"><legend>{{ es?'04 / Visibilidad':'04 / Visibility' }}</legend>
    <label class="agency-catalog-editor__publish"><input v-model="catalog.published" type="checkbox"><span><strong>{{ es?'Página pública':'Public page' }}</strong><small>{{ catalog.published ? (es?'Al guardar, tu presentación, contacto y artistas seleccionados serán visibles.':'Saving makes your bio, contact and selected artists visible.') : (es?'Tu página permanece privada. Puedes prepararla y ver la vista previa.':'Your page stays private. You can prepare it and review the preview.') }}</small></span></label>
    <p v-if="!readyToPublish" class="agency-catalog-editor__hint">{{ es?'Para publicar: presentación, email de booking y al menos un artista preparado.':'To publish: a bio, booking email and at least one ready artist.' }}</p>
    <div class="agency-catalog-editor__actions"><button type="submit">{{ saving ? (es?'Guardando…':'Saving…') : catalog.published ? (es?'Guardar y publicar':'Save and publish') : (es?'Guardar borrador':'Save draft') }}</button><button type="button" @click="openPreview">{{ es?'Vista previa':'Preview' }}</button><button v-if="savedPublished&&!demo" type="button" @click="copyLink">{{ es?'Copiar enlace':'Copy link' }}</button></div>
   </fieldset>
   <p v-if="savedPublished&&!demo" class="agency-catalog-editor__url"><a :href="publicUrl" target="_blank" rel="noopener">{{ publicUrl }}</a></p><p v-if="notice" class="agency-catalog-editor__notice" role="status">{{ notice }}</p>
  </form>
  <dialog ref="previewDialog" class="agency-catalog-preview" :aria-label="es?'Vista previa de la agencia':'Agency preview'"><div class="agency-catalog-preview__bar"><span>{{ es?'VISTA PREVIA · CONTENIDO SIN PUBLICAR':'PREVIEW · UNSAVED CONTENT' }}</span><button v-if="previewArtistId" type="button" @click="previewArtistId=''">← {{ es?'Artistas':'Artists' }}</button><button type="button" @click="previewDialog?.close()">{{ es?'Cerrar':'Close' }} ×</button></div><PublicArtistProfile v-if="demoProfile" :profile="demoProfile" :locale="locale" preview /><PublicAgencyProfile v-else-if="previewData" :agency="previewData" :locale="locale" preview :demo="demo" @open-artist="previewArtistId=$event" /></dialog>
 </section>
</template>
<style scoped>
.agency-catalog-editor{border-top:1px solid var(--cue-border);padding:22px 0}.agency-catalog-editor__label{font:700 10px monospace;color:var(--cue-accent);letter-spacing:.12em}.agency-catalog-editor h3{font-size:25px;letter-spacing:-.04em;margin:10px 0}.agency-catalog-editor p{font-size:12px;line-height:1.6;color:var(--cue-muted)}.agency-catalog-editor__fields{display:grid;grid-template-columns:1fr 1fr;gap:14px}.agency-catalog-editor form>label,.agency-catalog-editor__fields>label{display:grid;gap:7px;margin:12px 0;font-size:12px}.agency-catalog-editor input:not([type=checkbox]),.agency-catalog-editor textarea{box-sizing:border-box;width:100%;min-width:0;padding:11px;border:1px solid var(--cue-border);background:var(--cue-bg);color:var(--cue-text);font:inherit}.agency-catalog-editor fieldset{margin:20px 0;padding:14px;border:1px solid var(--cue-border)}.agency-catalog-editor legend{font-size:12px}.agency-catalog-editor__artist{display:flex;align-items:center;gap:10px;justify-content:space-between;padding:12px 0;border-top:1px solid var(--cue-border)}.agency-catalog-editor__artist label,.agency-catalog-editor__publish{display:flex!important;gap:10px;align-items:start}.agency-catalog-editor small{display:block;font-size:10px;color:var(--cue-muted);margin-top:5px}.agency-catalog-editor button{min-height:38px;padding:9px 12px;border:1px solid var(--cue-border);background:var(--cue-surface);color:var(--cue-text);cursor:pointer}.agency-catalog-editor button:disabled{opacity:.5}.agency-catalog-editor__actions{display:flex;flex-wrap:wrap;gap:8px}.agency-catalog-editor__actions button:first-child{background:var(--cue-accent);color:#151a11}.agency-catalog-editor__url{overflow-wrap:anywhere}.agency-catalog-editor__url a{color:var(--cue-accent)}.agency-catalog-editor__error{color:#ed8989!important}.agency-catalog-preview{width:calc(100vw - 24px);max-width:1500px;height:calc(100dvh - 24px);max-height:none;padding:0;background:var(--cue-bg);color:var(--cue-text);border:1px solid var(--cue-border)}.agency-catalog-preview::backdrop{background:#000c}.agency-catalog-preview__bar{position:sticky;top:0;z-index:10;display:flex;align-items:center;justify-content:space-between;padding:12px 20px;background:var(--cue-bg);border-bottom:1px solid var(--cue-border);font:10px monospace}@media(max-width:600px){.agency-catalog-editor__fields{grid-template-columns:1fr}.agency-catalog-editor__artist{align-items:start}.agency-catalog-preview__bar{padding:10px}}

.agency-catalog-editor{padding:36px 0}.agency-catalog-editor__heading{display:flex;align-items:flex-start;justify-content:space-between;gap:24px;margin-bottom:28px}.agency-catalog-editor h2{font-size:clamp(26px,3vw,40px);letter-spacing:-.04em;margin:8px 0}.agency-catalog-editor__status{flex-shrink:0;border:1px solid var(--cue-border);border-radius:var(--cue-radius-control);padding:8px 12px;font-size:11px;color:var(--cue-muted)}.agency-catalog-editor .agency-catalog-editor__group{padding:24px;margin:0 0 26px;border-radius:var(--cue-radius-panel);background:var(--cue-surface)}.agency-catalog-editor legend{font:700 12px/1.5 monospace;letter-spacing:.04em;padding:0 8px}.agency-catalog-editor__field{display:grid;gap:8px;margin:18px 0;font-size:12px}.agency-catalog-editor__optional{margin-top:20px;border-top:1px solid var(--cue-border);padding-top:18px}.agency-catalog-editor__optional summary{cursor:pointer;font-size:12px;min-height:28px}.agency-catalog-editor__artist{padding:16px 12px;margin-top:12px;border:1px solid var(--cue-border);border-radius:var(--cue-radius-control)}.agency-catalog-editor__artist.is-selected{border-color:color-mix(in srgb,var(--cue-toggle) 55%,var(--cue-border));background:color-mix(in srgb,var(--cue-toggle) 5%,var(--cue-surface))}.agency-catalog-editor__artist label{flex:1;cursor:pointer}.agency-catalog-editor__artist strong{font-size:13px}.agency-catalog-editor small{font-size:12px;line-height:1.5}.agency-catalog-editor__publish{padding:16px 0;cursor:pointer}.agency-catalog-editor__hint{border-left:3px solid #d6ab58;padding:10px 14px;background:color-mix(in srgb,#d6ab58 7%,var(--cue-surface))}.agency-catalog-editor__notice{border-left:3px solid var(--cue-toggle);padding:12px 16px;background:color-mix(in srgb,var(--cue-toggle) 7%,var(--cue-surface))}.agency-catalog-editor__error{border-left:3px solid #ed8989;padding:12px 16px;background:color-mix(in srgb,#ed8989 7%,var(--cue-surface))}.agency-catalog-editor button{min-height:44px;border-radius:var(--cue-radius-control)}.agency-catalog-editor input:not([type=checkbox]),.agency-catalog-editor textarea{border-radius:var(--cue-radius-control);font-size:14px;min-height:44px}.agency-catalog-editor__actions{margin-top:20px;gap:12px}.agency-catalog-editor__actions button:first-child{font-weight:700}@media(max-width:600px){.agency-catalog-editor__heading{flex-direction:column;gap:10px}.agency-catalog-editor .agency-catalog-editor__group{padding:18px 14px}.agency-catalog-editor__artist{flex-direction:column;align-items:stretch;gap:14px}.agency-catalog-editor__artist button{align-self:flex-start}.agency-catalog-editor__actions button{flex:1 1 140px}.agency-catalog-preview__bar{flex-wrap:wrap;gap:8px}}

.agency-catalog-editor__media-grid{display:grid;grid-template-columns:2fr 1fr;gap:24px;margin-top:28px}.agency-catalog-editor__media{min-width:0}.agency-catalog-editor__media h3{font-size:14px;letter-spacing:0;display:flex;align-items:center;gap:10px}.agency-catalog-editor__media h3 small{font-weight:400}.agency-catalog-editor__media-preview{aspect-ratio:16/9;border:1px solid var(--cue-border);border-radius:var(--cue-radius-control);background:var(--cue-bg);display:grid;place-items:center;overflow:hidden}.agency-catalog-editor__media-preview img{width:100%;height:100%;object-fit:cover}.agency-catalog-editor__media-preview.is-logo img{object-fit:contain;padding:20px;box-sizing:border-box}.agency-catalog-editor__media-preview span{padding:20px;color:var(--cue-muted);font-size:12px;text-align:center}.agency-catalog-editor__media-actions{display:flex;gap:10px;align-items:center}.agency-catalog-editor__media-picker{position:relative;display:inline-flex;align-items:center;justify-content:center;padding:0 14px;min-height:44px;cursor:pointer;border:1px solid var(--cue-border);border-radius:var(--cue-radius-control);font-size:12px}.agency-catalog-editor__media-picker input[type=file]{position:absolute;width:1px;height:1px;min-height:1px;padding:0;border:0;overflow:hidden;clip-path:inset(50%)}.agency-catalog-editor__media-picker:focus-within{outline:2px solid var(--cue-toggle);outline-offset:3px}fieldset:disabled .agency-catalog-editor__media-picker{opacity:.5;cursor:wait}@media(max-width:600px){.agency-catalog-editor__media-grid{grid-template-columns:1fr}}
</style>
