<script setup lang="ts">
import type { ConnectedMailbox } from '../services/connectedMailboxApi'
const props=defineProps<{workspaceId:string;locale:'es'|'en';demo?:boolean}>()
const api=useConnectedMailbox(),route=useRoute(),es=computed(()=>props.locale==='es')
const callbackNotice=ref('')
const loading=ref(false),busy=ref(false),configured=ref(false),error=ref(''),connections=ref<ConnectedMailbox[]>([]),email=ref(''),provider=ref('auto'),disconnectId=ref('')
const available=ref(true),waitlisted=ref(false),chooseProvider=ref(false)
let generation=0
const callbackMessage=computed(()=>{
 if(callbackNotice.value)return callbackNotice.value
 const state=String(route.query.mailbox||'')
 if(state==='authorize')return ''
 if(state==='connected')return es.value?'Correo conectado.':'Email connected.'
 if(state==='cancelled')return es.value?'Has cancelado la autorización.':'Authorization cancelled.'
 if(state==='account_mismatch')return es.value?'La cuenta autorizada no coincide con el correo indicado.':'The authorized account does not match the address entered.'
 if(state)return es.value?'No se completó la conexión. Vuelve a autorizar el correo.':'Connection was not completed. Authorize your email again.'
 return ''
})
async function joinWaitlist(){const turn=generation;busy.value=true;error.value='';try{const result=await api.waitlist(props.workspaceId);if(turn===generation)waitlisted.value=result.waitlisted}catch(e){if(turn===generation)error.value=message(e)}finally{busy.value=false}}
function message(e:unknown){const code=e instanceof Error?e.message:'';if(code==='mailbox_provider_selection_required'){chooseProvider.value=true;provider.value='';return es.value?'Elige dónde consultas este correo para continuar.':'Choose where you access this email to continue.'}if(code==='mailbox_beta_full'){available.value=false;return es.value?'Las plazas están completas. Puedes apuntarte a la lista de espera.':'Beta places are full. You can join the waiting list.'}return es.value?(code==='mailbox_not_configured'?'Estamos preparando la conexión de correo.':code==='workspace_access_denied'?'Tu rol no permite conectar correo.':code==='mailbox_attempt_limit'?'Hay demasiados intentos pendientes. Espera diez minutos.':'No se pudo completar la operación. Inténtalo de nuevo.'):'The operation could not be completed. Please retry.'}
async function load(){const turn=++generation,workspace=props.workspaceId;loading.value=true;error.value='';connections.value=[];configured.value=false;disconnectId.value='';available.value=true;waitlisted.value=false;chooseProvider.value=false;provider.value='auto';email.value='';try{if(!props.demo){if(import.meta.client){const params=new URLSearchParams(window.location.hash.slice(1)),code=params.get('mailbox_code'),state=params.get('mailbox_state');if(code&&state){window.history.replaceState(window.history.state,'',window.location.pathname+window.location.search);await api.complete(workspace,state,code);callbackNotice.value=es.value?'Correo conectado.':'Email connected.'}}const result=await api.status(workspace);if(turn===generation){configured.value=result.configured;connections.value=result.connections;available.value=result.beta.available;waitlisted.value=result.beta.waitlisted}}}catch(e){if(turn===generation)error.value=message(e)}finally{if(turn===generation)loading.value=false}}
async function connect(){if(busy.value||props.demo)return;busy.value=true;error.value='';const workspace=props.workspaceId;try{const result=await api.connect(workspace,email.value,provider.value);if(workspace!==props.workspaceId)return;const target=new URL(result.authorizationUrl);if(!['https://api.us.nylas.com','https://api.eu.nylas.com'].includes(target.origin)||target.pathname!=='/v3/connect/auth')throw new Error('invalid_redirect');window.location.assign(target.href)}catch(e){error.value=message(e)}finally{busy.value=false}}
async function disconnect(id:string){busy.value=true;error.value='';try{await api.disconnect(props.workspaceId,id);await load()}catch(e){error.value=message(e)}finally{busy.value=false}}
watch(()=>[props.workspaceId,props.demo],load,{immediate:true})
onBeforeUnmount(()=>{generation++})
function statusName(status:string){return es.value?(status==='connected'?'Conectado':status==='reconnect_required'?'Requiere autorización':'No se pudo verificar'):(status==='connected'?'Connected':status==='reconnect_required'?'Authorization required':'Could not verify')}
</script>
<template>
<section class="mailbox-panel" aria-labelledby="mailbox-heading" :aria-busy="loading||busy">
 <header><div><p class="mailbox-panel__eyebrow">{{es?'SOLICITUDES POR CORREO':'EMAIL ENQUIRIES'}}</p><h2 id="mailbox-heading">{{es?'Tu correo en Cuebooker':'Your email in Cuebooker'}}</h2></div><span class="mailbox-panel__badge">{{connections.some(c=>c.status==='connected')?(es?'Conectado':'Connected'):(es?'Sin conexión':'Disconnected')}}</span></header>
 <MailboxBetaNotice :locale="locale" />

 <p>{{es?'Conecta el buzón donde recibes solicitudes. Su conexión es personal; el equipo verá los mensajes que incorpores a un Booking.':'Connect the mailbox that receives enquiries. Its connection is personal; the team will see messages you attach to a Booking.'}}</p>
 <details class="mailbox-panel__ai"><summary>{{es?'Cómo funciona el análisis con IA':'How AI analysis works'}}</summary><p>{{es?'El análisis es opcional y requiere tu autorización. En esta beta enviamos a OpenAI el asunto y un fragmento del mensaje para sugerir si es una solicitud. Puede equivocarse: tú revisas el resultado y decides si crearla. La IA no responde ni confirma bookings por ti.':'Analysis is optional and requires your consent. In this beta we send the subject and a message excerpt to OpenAI to suggest whether it is an enquiry. It can make mistakes: you review the result and decide whether to create it. AI does not reply or confirm bookings for you.'}}</p></details>
 <p v-if="callbackMessage" class="mailbox-panel__notice" role="status">{{callbackMessage}}</p>
 <p v-if="loading" role="status">{{es?'Comprobando conexión…':'Checking connection…'}}</p>
 <p v-else-if="!configured" class="mailbox-panel__notice">{{demo?(es?'Vista de prueba. No conecta ni lee buzones reales.':'Preview. It does not connect or read real mailboxes.'):(es?'La conexión de correo está pendiente de activación.':'Email connection is awaiting activation.')}}</p>
 <article v-for="connection in connections" :key="connection.id" class="mailbox-panel__connection"><div><strong>{{connection.email}}</strong><small>{{connection.provider==='google'?'Gmail':connection.provider==='microsoft'?'Outlook / Hotmail':'IMAP'}} · {{statusName(connection.status)}}</small></div><button type="button" :disabled="busy" @click="disconnectId=connection.id">{{es?'Desconectar':'Disconnect'}}</button>
 <div v-if="disconnectId===connection.id" class="mailbox-panel__confirm"><p>{{es?'Cuebooker dejará de acceder a este buzón. Los Bookings existentes se conservan.':'Cuebooker will stop accessing this mailbox. Existing Bookings are retained.'}}</p><button type="button" :disabled="busy" @click="disconnect(connection.id)">{{es?'Confirmar desconexión':'Confirm disconnect'}}</button><button type="button" :disabled="busy" @click="disconnectId=''">{{es?'Volver':'Back'}}</button></div></article>
 <div v-if="configured&&!loading&&!available" class="mailbox-panel__notice"><p>{{es?'Las plazas de la beta están completas. Puedes consultar de nuevo más adelante.':'Beta places are full. You can check again later.'}}</p><p v-if="waitlisted" role="status">{{es?'Ya estás en la lista de espera. Tu interés ha quedado registrado.':'You are on the waiting list. Your interest has been recorded.'}}</p><button v-else type="button" :disabled="busy||demo" @click="joinWaitlist">{{es?'Apuntarme a la lista de espera':'Join waiting list'}}</button></div>
 <form v-if="available||connections.length" @submit.prevent="connect"><fieldset :disabled="busy||loading||!configured"><label><span>{{es?'Correo que quieres conectar':'Email to connect'}}</span><input v-model="email" type="email" autocomplete="email" maxlength="254" required placeholder="booking@tu-dominio.com" aria-describedby="mailbox-setup-help"></label><p id="mailbox-setup-help">{{es?'Escribe tu correo y autoriza la conexión. Después volverás a Cuebooker.':'Enter your email and authorize the connection. You will then return to Cuebooker.'}}</p><label v-if="chooseProvider"><span>{{es?'¿Dónde consultas este correo?':'Where do you access this email?'}}</span><select v-model="provider" required><option value="" disabled>{{es?'Selecciona tu servicio':'Select your service'}}</option><option value="google">Gmail / Google Workspace</option><option value="microsoft">Outlook / Hotmail / Microsoft 365</option><option value="imap">{{es?'Otro servicio de correo':'Another email service'}}</option></select></label><p class="mailbox-panel__privacy">{{es?'Autorizarás el acceso de Nylas en una pantalla segura. Algunos servicios pueden pedir una contraseña de aplicación o datos adicionales.':'Authorize Nylas access on a secure screen. Some services may require an app password or additional details.'}}</p><button class="mailbox-panel__connect" type="submit" :disabled="!available&&!connections.some(c=>c.email===email.trim().toLowerCase())">{{busy?(es?'Conectando…':'Connecting…'):(es?'Conectar correo':'Connect email')}}</button></fieldset></form>
 <p v-if="error" class="mailbox-panel__error" role="alert">{{error}}</p>
</section>
</template>
<style scoped>
.mailbox-panel{margin:28px 0;padding:24px;border:1px solid var(--cue-border);border-radius:var(--cue-radius-panel);background:var(--cue-surface);color:var(--cue-text)}.mailbox-panel header{display:flex;justify-content:space-between;align-items:start;gap:16px}.mailbox-panel h2{font-size:20px;margin:6px 0 16px}.mailbox-panel p{font-size:13px;line-height:1.6;color:var(--cue-muted)}.mailbox-panel__eyebrow{font:10px monospace;letter-spacing:.12em;margin:0}.mailbox-panel__badge{font:11px monospace;white-space:nowrap;padding:7px 10px;border:1px solid var(--cue-border);border-radius:var(--cue-radius-control);color:var(--cue-muted)}.mailbox-panel fieldset{border:0;padding:0;margin:20px 0 0;min-width:0}.mailbox-panel form{max-width:560px}.mailbox-panel label{display:grid;gap:8px;min-width:0;font-size:12px}.mailbox-panel input,.mailbox-panel select,.mailbox-panel button{box-sizing:border-box;min-height:44px;border:1px solid var(--cue-border);border-radius:var(--cue-radius-control);background:var(--cue-bg);color:var(--cue-text);font:inherit;font-size:12px;padding:10px 12px}.mailbox-panel input,.mailbox-panel select{width:100%;min-width:0}.mailbox-panel button{cursor:pointer}.mailbox-panel__ai{margin-top:14px}.mailbox-panel__ai summary{cursor:pointer;font-size:12px}.mailbox-panel__ai summary:focus-visible{outline:2px solid var(--cue-toggle);outline-offset:3px}.mailbox-panel :disabled{opacity:.5;cursor:default}.mailbox-panel input:focus-visible,.mailbox-panel select:focus-visible,.mailbox-panel button:focus-visible{outline:2px solid var(--cue-toggle);outline-offset:3px}.mailbox-panel .mailbox-panel__connect{background:var(--cue-accent);color:#080808;font-weight:700}.mailbox-panel__notice{border-left:3px solid #679cdc;background:color-mix(in srgb,#679cdc 9%,var(--cue-bg));padding:12px 16px;border-radius:var(--cue-radius-control)}.mailbox-panel__error{border-left:3px solid #e65e6a;background:color-mix(in srgb,#e65e6a 9%,var(--cue-bg));padding:12px 16px;border-radius:var(--cue-radius-control)}.mailbox-panel__connection{display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:14px;border-top:1px solid var(--cue-border);padding:16px 0}.mailbox-panel__connection strong{overflow-wrap:anywhere;font-size:13px}.mailbox-panel__connection small{display:block;color:var(--cue-muted);font-size:11px;margin-top:6px}.mailbox-panel__confirm{width:100%}.mailbox-panel__confirm button{margin:0 8px 8px 0}@media(max-width:600px){.mailbox-panel{padding:18px 14px}.mailbox-panel header{flex-direction:column;gap:0}.mailbox-panel__fields{grid-template-columns:1fr}.mailbox-panel h2{margin-bottom:12px}.mailbox-panel__badge{margin-bottom:10px}}
</style>
