import test from 'node:test';
import assert from 'node:assert/strict';
import {processMailboxIncoming} from '../supabase/functions/_shared/processMailboxIncoming.ts';
const job={id:'job',connectionId:'connection',workspaceId:'workspace',actorId:'actor',grantId:'grant',email:'dj@example.invalid',messageId:'mail',threadId:'thread',since:'2026-10-01T10:00:00Z'};
const raw={id:'mail',thread_id:'thread',date:1790849100,from:[{email:'promoter@example.invalid'}],to:[{email:job.email}],body:'Consulta',folders:['opaque-inbox']};
function setup(overrides:any={}){const calls:string[]=[];const options={authorize:async()=>{calls.push('authorize');return true},message:async()=>{calls.push('read');return raw},inbox:async()=>({inbox:['opaque-inbox'],excluded:['spam']}),linkedBooking:async()=>null,sync:async()=>{calls.push('sync')},classify:async()=>{calls.push('ai');return {id:'mail',kind:'booking' as const,reason:'Consulta'}},complete:async(state:string)=>{calls.push(state)},...overrides};return {calls,options}}
test('disabled/stale permission never reads message or calls AI',async()=>{const {calls,options}=setup({authorize:async()=>false});assert.equal(await processMailboxIncoming(job,options),'ignored');assert.deepEqual(calls,['ignored'])});
test('outgoing, pre-cutover and non-inbox messages never reach AI or booking sync',async()=>{
 for(const message of [{...raw,from:[{email:job.email}]},{...raw,date:1},{...raw,folders:['spam']},{...raw,folders:['spam','opaque-inbox']},{...raw,folders:[]},{...raw,id:'foreign'},{...raw,thread_id:'foreign'}]){const {calls,options}=setup({message:async()=>message});assert.equal(await processMailboxIncoming(job,options),'ignored');assert.equal(calls.includes('ai'),false);assert.equal(calls.includes('sync'),false)}
});
test('linked-thread reply syncs deterministically without classifying or creating a booking',async()=>{const {calls,options}=setup({linkedBooking:async()=> 'booking',sync:async(id:string,message:any)=>{assert.equal(id,'booking');assert.equal(message.id,'mail');calls.push('sync')}});assert.equal(await processMailboxIncoming(job,options),'synced');assert.equal(calls.includes('ai'),false);assert.equal(calls.includes('sync'),true)});
test('new eligible email records only a classification and never syncs or sends',async()=>{const {calls,options}=setup();assert.equal(await processMailboxIncoming(job,options),'classified');assert.deepEqual(calls,['authorize','read','authorize','ai','authorize','completed'])});
test('permission withdrawn during provider read prevents AI and sync',async()=>{let check=0;const {calls,options}=setup({authorize:async()=>++check===1});assert.equal(await processMailboxIncoming(job,options),'ignored');assert.equal(calls.includes('ai'),false)});
test('provider/model uncertainty is marked failed without retry',async()=>{let attempts=0;const {calls,options}=setup({classify:async()=>{attempts++;throw new Error('provider failure')}});assert.equal(await processMailboxIncoming(job,options),'failed');assert.equal(attempts,1);assert.equal(calls.at(-1),'failed')});
