from pathlib import Path

workspace = Path('app/pages/workspace.vue')
text = workspace.read_text()
old = '''        <div class="booking-tools">\n          <label class="booking-search">\n            <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="6"/><path d="m16 16 4 4"/></svg>\n            <span class="sr-only">{{ copy.searchBookings }}</span>\n            <input v-model="bookingSearch" type="search" :placeholder="copy.searchBookingsPlaceholder" :aria-label="copy.searchBookings">\n          </label>\n          <span class="booking-search-count">{{ demoFilteredBookings.length }} / {{ demoActiveBookings.length }} {{ copy.searchResults }}</span>\n        </div>\n\n        <div id="workspace-filters" class="status-filters" :class="{ 'tour-focus': tourStep === 1 }" :aria-label="copy.filterSamples">\n          <button :class="{ active: bookingFilter === 'all' }" type="button" @click="bookingFilter = 'all'">{{ copy.all }} <strong>{{ demoActiveBookings.length }}</strong></button>\n          <button v-for="status in bookingStatuses.filter(item => item !== 'rejected')" :key="status" type="button" :class="[{ active: bookingFilter === status }, `tone-${statusTone[status]}`]" @click="bookingFilter = status"><i />{{ demoStatusLabel(status) }} <strong>{{ demoCounts[status] }}</strong></button>\n        </div>'''
new = '''        <div class="booking-toolbar-row">\n          <div class="booking-tools">\n            <label class="booking-search">\n              <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="6"/><path d="m16 16 4 4"/></svg>\n              <span class="sr-only">{{ copy.searchBookings }}</span>\n              <input v-model="bookingSearch" type="search" :placeholder="copy.searchBookingsPlaceholder" :aria-label="copy.searchBookings">\n            </label>\n          </div>\n\n          <div id="workspace-filters" class="status-filters" :class="{ 'tour-focus': tourStep === 1 }" :aria-label="copy.filterSamples">\n            <button :class="{ active: bookingFilter === 'all' }" type="button" @click="bookingFilter = 'all'">{{ copy.all }} <strong>{{ demoActiveBookings.length }}</strong></button>\n            <button v-for="status in bookingStatuses.filter(item => item !== 'rejected')" :key="status" type="button" :class="[{ active: bookingFilter === status }, `tone-${statusTone[status]}`]" @click="bookingFilter = status"><i />{{ demoStatusLabel(status) }} <strong>{{ demoCounts[status] }}</strong></button>\n          </div>\n\n          <span class="booking-search-count">{{ demoFilteredBookings.length }} / {{ demoActiveBookings.length }} {{ copy.searchResults }}</span>\n        </div>'''
if old not in text:
    raise SystemExit('booking toolbar block not found')
workspace.write_text(text.replace(old, new, 1))

css = Path('assets/css/workspace-responsive-final.css')
css_text = css.read_text()
block = '''\n\n/* Canonical bookings toolbar structure. */\n.booking-toolbar-row {\n  display: grid;\n  grid-template-columns: minmax(0, 1fr);\n  gap: 10px;\n  margin: 0 0 12px;\n}\n\n.booking-toolbar-row .booking-tools,\n.booking-toolbar-row .status-filters {\n  margin: 0 !important;\n}\n\n@media (min-width: 1280px) {\n  .workspace .bookings-view {\n    display: block !important;\n  }\n\n  .workspace .booking-toolbar-row {\n    grid-template-columns: minmax(360px, 460px) max-content minmax(90px, 1fr);\n    align-items: center;\n    column-gap: 12px;\n    row-gap: 0;\n  }\n\n  .workspace .booking-toolbar-row .booking-tools {\n    display: block !important;\n    width: 100%;\n  }\n\n  .workspace .booking-toolbar-row .booking-search {\n    width: 100%;\n    max-width: none;\n  }\n\n  .workspace .booking-toolbar-row .status-filters {\n    display: flex !important;\n    flex-wrap: nowrap !important;\n    align-items: center;\n    gap: 8px;\n  }\n\n  .workspace .booking-toolbar-row .status-filters > button {\n    flex: 0 0 auto;\n    white-space: nowrap;\n  }\n\n  .workspace .booking-toolbar-row .booking-search-count {\n    justify-self: end;\n    white-space: nowrap;\n  }\n}\n\n@media (max-width: 1279px) and (min-width: 961px) {\n  .workspace .booking-toolbar-row {\n    grid-template-columns: minmax(320px, 1fr) auto;\n  }\n\n  .workspace .booking-toolbar-row .status-filters {\n    grid-column: 1 / -1;\n  }\n\n  .workspace .booking-toolbar-row .booking-search-count {\n    justify-self: end;\n  }\n}\n\n@media (max-width: 960px) {\n  .workspace .booking-toolbar-row {\n    display: block;\n    margin-bottom: 8px;\n  }\n\n  .workspace .booking-toolbar-row .booking-search-count {\n    display: block;\n    margin: 6px 0;\n  }\n}\n'''
if block.strip() not in css_text:
    css_text += block
css.write_text(css_text)
